// Icelandic absurd conditions for the Adult Mode Generator
export const absurdConditions = [
    "Líklegast til að vera í tímaferðalaga-rannsóknarlögreglunni",
    "Vann störukeppni við sólina og birtist núna sem geislandi ljós",
    "Kann að lesa hugsanir en bara meðan það er opinn eldur nálægt",
    "Hefur vingast við geimverur og er í stöðugu sambandi við þær",
    "Hefur annað form og breytir sér eftir geðslagi sínu",
    "Dýrið sem er líklegast ekki til í alvörunni",
    "Þríhyrningslagaðasta dýrið",
    "Ef þetta dýri yrði sent út í geim myndi mannkynið geta búið á tunglinu",
    "Býr á tunglinu og sendir veikustu meðlimi hjarðarinnar til jarðarinnar til að safna upplýsingum",
    "Skuggi dýrsins er dýrið sjálft",
    "Dýrið sem er mesti spírallinn",
    "Myndi líklega prjóna peysu úr stjörnuljósi",
    "Dýrið sem gat marmelaði",
    "Þróaðist úr hafmeyjum",
    "Hefur flesta ósýnilega útlimi",
    "Lyktin af því finnst eingöngu í þátíð",
    "Getur ekki talað við dýr af sinni tegund, nema þau séu steingervingar",
    "Dýrið sem getur ekki verið í herbergi með spegli",
    "Getur flogið, en aðeins á bak við tunglið",
    "Gimsteinar verða til þegar þetta dýr heyrir jólalag",
    "Er skylt dýrum sem lifa í öðrum víddum",
    "Getur ekki verið í herbergi með opnum glugga",
    "Getur aðeins synt aftur á bak",
    "Sér fram í tímann",
    "Getur stýrt flugum með hugarorku",
    "Getur ekki litið í augu annarra dýra",
    "Getur aðeins hreyft sig þegar enginn er að horfa",
    "Fann upp rauðan",
    "Segir eitthvað upphátt og það verður satt",
    "Birtist fólki í draumum þegar það á von á lottóvinningi",
    "Hefur bein áhrif á veðrið",
    "Er með fjóra maga umfram það sem áður hefur verið talið",
    "Geðslag þessa dýrs er það sem stjórnar árstíðum",
    "Ef dýrið fer í hring til vinstri við þig þá geturðu gleymt öllum vandamálum þínum",
    "Brennur og lifnar við, þegar það vill",
    "Felur á sér auka tá",
    "Kann ekki að gefa frá sér hljóð, öll hljóð sem þú telur þig hafa heyrt frá því er ímyndun",
    "Ekki reyna að snerta dýrið, því þá verður til vondur snigill einhversstaðar annars staðar í heiminum",
    "Raftæki hafa áhrif á getu dýrsins til að senda hugskeyti í móðurskipið",
    "LED ljós valda því að dýrið missir tímaskyn",
    "Hringlaga hlutir draga úr hæfni dýrsins til að nota laser sjónina",
    "Getur blásið eldi",
    "Getur skotið ísmolum úr augunum",
    "Hefur aldrei horft upp",
    "Geymir internetið",
    "Er með augu bakvið augun, hvorugt eru augu dýrsins samt",
    "Þetta dýr dó út fyrir löngu, allir einstaklingarnir eru klón af upprunalegu dýrinu",
    "Hefur aldrei séð vatn",
    "Er bara ljósmynd, dýrið er blekking",
    "Samdi við tunglið um að fá að lifa á jörðinni",
    "Framkvæmdastjóri draumalandsins",
    "Framkvæmdastjóri martraðalandsins",
    "Er teiknað, ekki raunverulegt dýr",
    "Getur svifið í lofti"

];
