// English absurd conditions for the Adult Mode Generator
export const absurdConditions = [
    "Most likely to become a time-traveling detective",
    "Would definitely win a staring contest with the sun",
    "Most likely to invent teleportation while doing laundry",
    "Would probably befriend aliens through interpretive dance",
    "Most likely to solve world hunger with magical powers",
    "Would definitely become emperor of the ocean",
    "Most likely to discover that clouds are actually cotton candy",
    "Would probably teach philosophy to interdimensional beings",
    "Most likely to open a restaurant on the moon",
    "Would definitely become best friends with their own shadow",
    "Most likely to negotiate peace treaties between parallel universes",
    "Would probably knit sweaters out of starlight",
    "Most likely to convince gravity to work backwards",
    "Would definitely become the CEO of imagination",
    "Most likely to translate ancient memes for future civilizations",
    // Translated from Icelandic
    "Most likely to be in the time-travel police department",
    "Won a strength competition against the sun and now appears as radiant light",
    "Can read thoughts but only when there's an open fire nearby",
    "Has befriended aliens and is in constant contact with them",
    "Has another form and changes according to their mood",
    "Most likely doesn't actually exist",
    "Most triangular-shaped animal",
    "If this animal were sent into space, humans could live on the moon",
    "Lives on the moon and sends the weakest members of the herd to earth to gather information",
    "The animal's shadow is the animal itself",
    "Most spiral-like animal",
    "Would probably knit a sweater out of starlight",
    "Can lay marmalade like eggs",
    "Evolved from mermaids",
    "Has the most invisible limbs",
    "Its scent can only be detected in past tense",
    "Cannot talk to animals of its own species unless they are stone statues",
    "Cannot be in a room with a mirror",
    "Can fly, but only behind the moon",
    "Gems are created when this animal hears Christmas music",
    "Is related to animals that live in other dimensions",
    "Cannot be in a room with open windows",
    "Can only swim backwards",
    "Sees into the future",
    "Can control flies with mind power",
    "Cannot look into other animals' eyes",
    "Can only move when no one is watching",
    "Invented the color red",
    "Says something out loud and it becomes true",
    "Appears to people in dreams when they're expecting to win the lottery",
    "Has direct influence on the weather",
    "Has four more stomachs than previously thought possible",
    "This animal's mood controls the seasons",
    "If the animal circles to your left, you can forget all your problems",
    "Burns and resurrects when it wants to",
    "Hides an extra toe",
    "Cannot make sounds; all sounds you think you've heard from it are imagination",
    "Don't try to touch the animal, because then an evil snail will be created somewhere else in the world",
    "Electronic devices affect the animal's ability to send mind messages to the mothership",
    "LED lights cause the animal to lose its sense of time",
    "Round objects reduce the animal's ability to use laser vision",
    "Can breathe fire",
    "Can shoot ice balls from its eyes",
    "Has never looked up",
    "Stores the internet",
    "Has eyes behind its eyes, though neither are actually the animal's eyes",
    "This animal died out long ago; all individuals are clones of the original animal",
    "Has never seen water",
    "Is just a photograph; the animal is an illusion",
    "Made a deal with the moon to be allowed to live on earth"
];
