// Icelandic fan-made conditions for the Adult Mode Generator
// These should all contain a ______ structure similar to "Most likely to ______" or "Would definitely ______"
export const fanMadeConditions = [
    "Líklegast til að ________ komi fyrir það",
    "Myndi örugglega ________",
    "Líklegast til að fá sitt eigið ________",
    "Myndi örugglega leika aðalhlutverkið í ________",
    "Líklegast til að verða frægur YouTuber fyrir ________",
    "Myndi örugglega vinna raunveruleikaþáttakeppni um ________",
    "Líklegast til að ævisagan titluð: ________ verði að metsölubók",
    "Myndi örugglega verða atvinnu tölvuleikjaspilari í ________",
    "Líklegast til að fá sitt eigið þema garðaðdráttarafl sem heitir ________",
    "Myndi örugglega verða veiru TikTok stjarna fyrir ________",
    "Líklegast til að birtast á hvatningarplakati með textanum ________",
    "Myndi örugglega stýra eigin spjallþætti sem heitir ________",
    "Líklegast til að ________ fyrir ________",
    "Myndi örugglega vera í náttúru heimildarmynd um ________",
    "Líklegast til að uppgötva stjörnu og nefna hana ________",
    "Líklegast til að geta ________ ",
    "Líklegast til að vilja ________ ",
    "Líklegast til að þurfa ________ á hverjum degi",
    "Líklegast til að verða frægur fyrir ________ ",
    "Líklegast til að ferðast til ________ ",
    "Líklegast til að eignast ________ sem gæludýr",
    "Líklegast til að fá ________ í afmælisgjöf",
    "Líklegast til að borða ________ í hádegismat",
    "Líklegast til að klæðast ________ á hverjum degi",
    "Líklegast til að syngja ________ í sturtu",
    "Líklegast til að dansa við ________ á partýi",
    "Líklegast til að skrifa bók um ________ ",
    "Líklegast til að vinna verðlaun fyrir ________ ",
    "Líklegast til að verða þekktur fyrir hæfileika sína í ________ ",
    "Líklegast til að byrja daginn með ________ ",
    "Líklegast til að eyða frítíma sínum í ________ ",
    "Líklegast til að læra nýja færni í ________ ",
    "Líklegast til að verða sérfræðingur í ________ ",
    "Líklegast til að halda fyrirlestur um ________ ",
    "Líklegast til að taka þátt í keppni um ________ ",
    "Líklegast til að búa til uppfinningu sem hjálpar við ________ ",
    "Líklegast til að ferðast um heiminn til að rannsaka ________ ",
    "Líklegast til að stofna félag um áhugamál sitt í ________ ",
    "Líklegast til að verða frægur fyrir að hjálpa við ________ ",
    "Líklegast til að verða boðberi ________ ",
    "Líklegast til að verða áhrifavaldur í ________ ",
    "Mest fyrir að fara í ________ ",
    "Dýrið sem safnar ________ ",
    "Dýrið sem elskar ________ ",
    "Dýrið sem hatar ________ ",
    "Dýrið sem hættir ekki að tala um ________ ",
    "Dýrið sem dreymir um ________ ",
    "Dýrið sem vill alltaf ________ ",
    "Dýrið sem getur ekki hætt að ________ ",
    "Dýrið sem er alltaf að leita að ________ ",
    "Dýrið sem er þekktast fyrir ________ ",
    "Dýrið sem er best í ________ ",
    "Dýrið sem er frægast fyrir ________ ",
    "Dýrið sem getur ekki lært að ________ ",
    "Dýrið sem er alltaf að reyna að ________ ",
    "Dýrið sem er mest spennt fyrir ________ ",
    "Dýrið sem er alltaf að hugsa um ________ ",
    "Dýrið sem kom einu sinni fram með ________ ",
    "Dýrið sem hefur mestan áhuga á ________ ",
    "Dýrið sem reynir aftur og aftur að ________ ",
    "Dýrið sem reyndi að ________ en mistókst",
    "Dýrið sem hefur áhuga á ________ þó að það ________ ",
    "Dýrið sem reyndi að ________ og tókst það",
    "Dýrið sem neitar að ________ ",
    "Dýrið sem þarf að viðurkenna að ________",
    "Dýrið sem er alltaf að leita að ________ ",
    "________ hefur aldrei komið fyrir dýrið",
    "________ gerist alltaf þegar dýrið reynir að ________ ",
    "Dýrið sem myndi örugglega ________ ef það gæti",
    "________ gerðist þegar dýrið ________",
    "________ gæti ekki stoppað dýrið frá því að ________ ",
    "________ er það eina sem dýrið vill gera",
    "________ er það eina sem dýrið getur ekki hætt að gera",
    "________ gæti komið dýriu í klandur",
    "________ væri sjónvarpsþáttur um dýrið",
    "________ væri titillinn á frétt um dýrið",
    "Frægustu orð dýrsins eru ________ ",
    "Dýrið ætti að leggja sig meira fram við að ________",
    "Gætið verið að ________ sé dýrinu að kenna?",
    "Hættu nú alveg! ________ er ekki dýrinu að kenna!",
    "Ekki segja mér að dýrið hafi aftur ________!",
    "Ég þekki dýrið það gæti ekki hafa ________!",
    "Dýrið myndi aldrei ________!",
    "Ég trúi því ekki að dýrið hafi ________!",
    "Þú veist ekki hvað dýrið er fært um, ég sá það ________",
    "Ég þyrfti að fá dýr sem gæti ________ til að hjálpa mér við að ________",
    "Láttu ekki svona, ekkert dýr getur ________",
    "Það var búið til myllumerki fyrir dýrið: #______",
    "Það þarf að bjarga þessu dýri frá ________",
    "Dýrið þarf að læra að ________ áður en það getur ________",
    "Dýrið er þekkt fyrir að ________ á óvæntum stöðum",
    "Ég gæti alveg hugsað mér að eiga dýr sem getur ________",
    "Ég þarf bara að ________ til að geta átt þetta dýr",
    "Dýrið myndi líklega ________ ef það fengi tækifæri",
    "Dýrið er alltaf að reyna að finna leið til að ________",
    "Ekki nein læti! Og ekki hreyfa þig, dýrið gæti ________!",
    "Aldrei að segja aldrei! Þetta dýr gæti alveg ________ einn daginn",
    "Ef ________, þá gæti dýrið ________",


];
