// English fan-made conditions for the Adult Mode Generator
export const fanMadeConditions = [
    "Most likely to appear in a superhero movie",
    "Would definitely be the main character in a fantasy novel",
    "Most likely to have their own cooking show",
    "Would probably star in a romantic comedy",
    "Most likely to become a famous YouTuber",
    "Would definitely win a reality TV competition",
    "Most likely to have their biography turned into a bestseller",
    "Would probably become a professional video game streamer",
    "Most likely to get their own theme park attraction",
    "Would definitely become a viral TikTok sensation",
    "Most likely to appear on a motivational poster",
    "Would probably host their own talk show",
    "Most likely to become a fashion influencer",
    "Would definitely be featured in a nature documentary",
    "Most likely to have a constellation named after them",
    // Translated from Icelandic
    "Most likely to ________ happen to them",
    "Would definitely ________",
    "Most likely to get their own ________",
    "Would definitely play the lead role in ________",
    "Most likely to become a famous YouTuber for ________",
    "Would definitely win a reality show competition about ________",
    "Most likely to have their biography titled: ________ become a bestseller",
    "Would definitely become a professional video game player in ________",
    "Most likely to get their own theme park ride called ________",
    "Would definitely become a viral TikTok star for ________",
    "Most likely to appear on a motivational poster with the text ________",
    "Would definitely host their own talk show called ________",
    "Most likely to ________ for ________",
    "Would definitely be in a nature documentary about ________",
    "Most likely to discover a star and name it ________",
    "Most likely to be able to ________",
    "Most likely to want to ________",
    "Most likely to need ________ every day",
    "Most likely to become famous for ________",
    "Most likely to travel to ________",
    "Most likely to own ________ as a pet",
    "Most likely to get ________ as a birthday gift",
    "Most likely to eat ________ for lunch",
    "Most likely to wear ________ every day",
    "Most likely to sing ________ in the shower",
    "Most likely to dance to ________ at parties",
    "Most likely to write a book about ________",
    "Most likely to win awards for ________",
    "Most likely to become known for their skills in ________",
    "Most likely to start the day with ________",
    "Most likely to spend free time ________",
    "Most likely to learn new skills in ________",
    "Most likely to become an expert in ________",
    "Most likely to give lectures about ________",
    "Most likely to participate in competitions about ________",
    "Most likely to create an invention that helps with ________",
    "Most likely to travel the world to research ________",
    "Most likely to start a club about their hobby in ________",
    "Most likely to become famous for helping with ________",
    "Most likely to become an ambassador for ________",
    "Most likely to become an influencer in ________",
    "Most into going to ________",
    "Collects ________",
    "Loves ________",
    "Hates ________",
    "Won't stop talking about ________",
    "Dreams about ________",
    "Always wants to ________",
    "Can't stop ________",
    "Is always looking for ________",
    "Is best known for ________",
    "Is best at ________",
    "Is most famous for ________",
    "Can't learn to ________",
    "Is always trying to ________",
    "Is most excited about ________",
    "Is always thinking about ________",
    "Once performed with ________",
    "Has the most interest in ________",
    "Tries again and again to ________",
    "Tried to ________ but failed",
    "Has interest in ________ even though it ________",
    "Tried to ________ and succeeded",
    "Refuses to ________",
    "Needs to admit that ________",
    "Is always looking for ________",
    "________ has never happened to this animal",
    "________ always happens when the animal tries to ________",
    "Would definitely ________ if it could",
    "________ happened when the animal ________",
    "________ couldn't stop the animal from ________",
    "________ is the only thing the animal wants to do",
    "________ is the only thing the animal can't stop doing",
    "________ could get the animal in trouble",
    "________ would be a TV show about the animal",
    "________ would be the headline of news about the animal",
    "The animal's most famous words are ________",
    "The animal should try harder to ________",
    "Could it be that ________ is the animal's fault?",
    "Stop it! ________ is not the animal's fault!",
    "Don't tell me the animal has ________ again!",
    "I know the animal, it couldn't have ________!",
    "The animal would never ________!",
    "I can't believe the animal has ________!",
    "You don't know what the animal is capable of; I saw it ________",
    "I would need an animal that could ________ to help me ________",
    "Don't be like that; no animal can ________",
    "A hashtag was created for the animal: #________",
    "This animal needs to be saved from ________",
    "The animal needs to learn to ________ before it can ________",
    "The animal is known for ________ in unexpected places",
    "I could totally imagine having an animal that can ________",
    "I just need to ________ to be able to own this animal",
    "The animal would probably ________ if given the chance",
    "The animal is always trying to find a way to ________",
    "No fuss! And don't move; the animal might ________!",
    "Never say never! This animal could totally ________ someday",
    "If ________, then the animal could ________"
];
