// English realistic conditions for the Adult Mode Generator
export const realisticConditions = [
    "Has the strongest bite force relative to body size",
    "Can survive the longest periods without food",
    "Has the most acute sense of smell",
    "Can maintain the highest body temperature in cold environments",
    "Has the most efficient cardiovascular system",
    "Can process toxins most effectively",
    "Has the best camouflage abilities for avoiding predators",
    "Can travel the greatest distances without rest",
    "Has the most sophisticated social communication system",
    "Can adapt to the widest range of environmental conditions",
    "Has the most efficient hunting strategy for its size",
    "Can survive at the highest altitudes",
    "Has the best memory for spatial navigation",
    "Can regenerate lost body parts most effectively",
    "Has the most energy-efficient locomotion method",
    // Translated from Icelandic
    "Has the strongest bite force relative to body size",
    "Can survive the longest without food",
    "Has the most sensitive sense of smell",
    "Can endure the most cold",
    "Has the most efficient circulatory system",
    "Can process toxins best",
    "Has the best hiding methods to avoid predators",
    "Can travel the longest distances without rest",
    "Has the most complex communication system",
    "Best at adapting to new climates",
    "Has the most efficient hunting method relative to size",
    "Can live at the highest altitude",
    "Has the best memory",
    "Can recover from injuries fastest",
    "Most energy-efficient animal",
    "Most likely to accidentally end up in a car ride",
    "Scratches the most",
    "Most wants to just stay home with their parents",
    "Least wants to be home with their parents",
    "Changes color most often",
    "Found a rock and is always with it",
    "Just wants to look up at clouds all day",
    "Always wants to stretch",
    "Has the largest tongue",
    "Can stay awake the longest",
    "Just wants to go to sleep right now",
    "Coolest animal",
    "Most awesome animal",
    "Fiercest animal",
    "Best swimmer",
    "Lives closest to the center of the earth",
    "Sweetest animal",
    "Cutest animal",
    "Worst smelling animal",
    "Stickiest animal",
    "Slipperiest animal",
    "Ugliest animal",
    "Has the largest teeth",
    "Has the largest eyes",
    "Has the smallest claws",
    "Has the smallest brain",
    "Has the smallest feet",
    "Most dangerous animal",
    "Most likely to live in a cave",
    "Most likely to be up in a tree",
    "Most likely to be found up on a mountain",
    "Most closely related to humans",
    "Can sleep the most at once",
    "Most poisonous animal",
    "Would win in a fight",
    "Most likely to complain about the food",
    "Strangest animal",
    "Most likely to hide under a summer house",
    "Most likely to learn sign language",
    "Has the largest ears",
    "Is closest to the earth's surface",
    "Most likely to lick your hand",
    "Fattest animal",
    "Thinnest animal",
    "Found highest up in the air",
    "Has the hardest shell",
    "Would best fit in a cardboard box",
    "Hairiest animal",
    "Slowest animal",
    "Fastest animal",
    "Has the most beautiful name",
    "Best picture",
    "Most likely to sniff flowers",
    "Most likely to be a villain in a horror movie",
    "Could put out a fire",
    "Most harmless animal",
    "Most wants to be in a hole",
    "Best at climbing",
    "Best at hiding",
    "Most wants to be sunbathing",
    "Goes abroad every year",
    "Most wants to be underground",
    "Most wants to be underwater",
    "Most likely to avoid water",
    "Best at healing",
    "Best at picking their nose",
    "Best at eating a lot at once",
    "Has been on earth the longest",
    "Most wants to be in darkness",
    "Eats most rarely",
    "Most endangered",
    "Most common in zoos",
    "Can jump the highest",
    "Can make the loudest noise",
    "Has the best vision",
    "Sees best in the dark",
    "Has the most teeth",
    "Has the fewest teeth",
    "Can live the longest without water",
    "Can live the longest without food",
    "Can be closest to humans",
    "Can tolerate the most heat",
    "Most often needs to defend itself",
    "Eats the most plants",
    "Eats the most meat",
    "Most likely to become a pet"
];
