// Icelandic realistic conditions for the Adult Mode Generator
export const realisticConditions = [
    "Hefur sterkasta bitstyrkinn miðað við líkamsstærð",
    "Getur lifað lengst án matar",
    "Hefur næmasta lyktarskyn",
    "Getur haldið út í mestum kulda",
    "Hefur skilvirkasta blóðrásarkerfið",
    "Getur unnið úr eiturefnum best",
    "Hefur bestu feluaðferðirnar til að forðast rándýr",
    "Getur ferðast lengstu vegalengdirnar án hvíldar",
    "Hefur flóknasta samskiptakerfið",
    "Best í að aðlagað sig að nýju loftslagi",
    "Hefur skilvirkustu veiðiaðferðina miðað við stærð",
    "Getur lifað í hæstu hæð",
    "Hefur besta minnið",
    "Getur jafnað sig eftir meiðsli hraðast",
    "Orkunýtnasta dýrið",
    "Dýrið sem fer oftast óvart í bílferð",
    "Dýrið sem klæjar mest",
    "Dýrið sem þráir að vera bara heima hjá foreldrum sínum",
    "Dýrið sem vill alls ekki vera heima hjá foreldrum sínum",
    "Dýrið sem skiptir oftast um lit",
    "Dýrið sem fann sér stein, og er alltaf hjá honum",
    "Dýrið sem vill bara horfa upp í skýin allan daginn",
    "Dýrið sem vill alltaf teygja úr sér",
    "Dýrið með stærstu tunguna",
    "Dýrið sem hgetur vakið lengst",
    "Dýrið sem vill bara fara að sofa núna",
    "Flottasta dýrið",
    "Svalasta dýrið",
    "Grimmasta dýrið",
    "Dýrið sem syndir best",
    "Dýrið sem býr næst miðju jarðar",
    "Sætasta dýrið",
    "Krúttlegasta dýrið",
    "Mest illa lyktandi dýrið",
    "Klístraðasta dýrið",
    "Sleipasta dýrið",
    "Ljótasta dýrið",
    "Dýrið með stærstu tennurnar",
    "Dýrið með stærstu augun",
    "Dýrið með minnstu klærnar",
    "Dýrið með minnsta heilann",
    "Dýrið með minnstu fæturna",
    "Hættulegasta dýrið",
    "Dýrið sem er líklegast til að búa í helli",
    "Dýrið sem er líklegast til að vera uppi í tré",
    "Dýrið sem er líklegast til að finnast uppi á fjalli",
    "Dýrið sem er skyldast mönnum",
    "Dýrið sem getur sofið mest í einu",
    "Eitraðasta dýrið",
    "Dýrið sem myndi vinna í slag",
    "Dýrið sem er líklegast til að kvarta yfir matnum",
    "Skrýtnasta dýrið",
    "Dýrið sem er líklegast til að fela sig undir sumarbústað",
    "Dýrið sem er líklegast til að læra táknmál",
    "Dýrið með stærstu eyrun",
    "Dýrið sem er hvað næst yfirborði jarðarinnar",
    "Dýrið sem er líklegast til að sleikja á þér höndina",
    "Feitasta dýrið",
    "Mjóasta dýrið",
    "Dýrið sem finnst hærra uppi í loftinu",
    "Dýrið með harðasta gogginn",
    "Dýrið sem gæti passað best ofan í pappakassa",
    "Loðnasta dýrið",
    "Hægasta dýrið",
    "Hraðasta dýrið",
    "Dýrið með fallegasta nafnið",
    "Flottasta myndin",
    "Dýrið sem er líklegast til að þefa af blómum",
    "Dýrið sem er líklegast til að vera óvinur í hryllingsmynd",
    "Dýrið sem gæti slökkt eld",
    "Meinlausasta dýrið",
    "Dýrið sem langar mest að vera ofan í holu",
    "Dýrið sem er best í að klifra",
    "Dýrið sem er best í að fela sig",
    "Dýrið sem vill helst vera í sólbaði",
    "Dýrið sem fer til útlanda á hverju ári",
    "Dýrið sem vill helst vera neðanjarðar",
    "Dýrið sem vill helst vera neðansjávar",
    "Dýrið sem er líklegast til að forðast vatn",
    "Dýrið sem er best í að lækna",
    "Dýrið sem er best í að bora í nefið",
    "Best i að borða mikið í einu",
    "Dýrið sem hefur verið til lengst á jörðinni",
    "Dýrið sem vill vera oftast í myrkri",
    "Dýrið sem borðar sjaldnast",
    "Dýrið sem er í mestri útrýmingarhættu",
    "Dýrið sem er algengast í dýragörðum",
    "Dýrið sem getur hoppað hæst",
    "Dýrið sem getur búið til mesta hávaðann",
    "Dýrið sem sér best",
    "Dýrið sem sér best í myrkri",
    "Dýrið sem hefur flestar tennur",
    "Dýrið sem hefur fæstar tennur",
    "Dýrið sem getur lifað lengst án vatns",
    "Dýrið sem getur lifað lengst án matar",
    "Dýrið sem getur verið næst mannfólki",
    "Dýrið sem þolir mestan hita",
    "Dýrið sem þarf oftast að forða sér",
    "Dýrið sem borðar mest af plöntum",
    "Dýrið sem borðar mest af kjöti",
    "Dýrið sem er líklegast til að verða húsdýr",
];
