// Icelandic weird conditions for the Adult Mode Generator
export const weirdConditions = [
    "Dýrið sem er líklegast til að vera í sirkús",
    "Dýrið sem er líklegast til að vera gæludýr",
    "Dýrið sem er líklegast til að vera í sundlaug",
    "Dýrið sem er líklegast til að vera forseti",
    "Dýrið sem er líklegast til að borða mús",
    "Dýrið sem er líklegast til að búa á Íslandi",
    "Dýrið sem er líklegast til að lukkudýr fyrir sundlaugagarð",
    "Dýrið sem er líklegast til að lukkudýr fyrir klukkufyrirtæki",
    "Dýrið sem er líklegast til að tala mikið í síma",
    "Dýrið sem er líklegast til að ganga með bakpoka",
    "Dýrið sem er líklegast til að vera gæludýr forseta Íslands",
    "Dýrið sem er líklegast til að skrifa bók um líf sitt",
    "Dýrið sem er líklegast til að heimsækja bókasafn",
    "Dýrið sem er líklegast til að elda",
    "Dýrið sem er líklegast til að sofa uppi á háalofti",
    "Dýrið sem er líklegast til að spila á hljóðfæri",
    "Dýrið sem er líklegast til að koma í fréttunum",
    "Dýrið sem er líklegast til að læra að lesa",
    "Dýrið sem er líklegast til að finnast í heitum potti",
    "Dýrið sem er líklegast til að hafa það kózý upp í sófa",
    "Dýrið sem er líklegast til að fara á hestbak",
    "Dýrið sem er líklegast til að nota gleraugu",
    "Dýrið sem er líklegast til að fá sér göt í eyrun",
    "Dýrið sem er líklegast til að panta súrdeigspizzu",
    "Dýrið sem er líklegast til að fara út í ostagerð",
    "Dýrið sem er líklegast til að vera í góðu skapi",
    "Dýrið sem er líklegast til að vera í vondu skapi",
    "Dýrið sem er líklegast til að vilja verða vinur þinn",
    "Dýrið sem er líklegast til að kynna nýjan búðing í Hagkaup",
    "Dýrið sem er líklegast til að keppa í badminton",
    "Dýrið sem er líklegast til að gerast danskur húsgagnahönnuður",
    "Dýrið sem er líklegast til að hanna tölvuleiki",
    "Dýrið sem er líklegast til að hanna nýjar tegundir af pasta",
    "Dýrið sem er líklegast til að nudda annað dýr",
    "Dýrið sem er líklegast til að prjóna trefil",
    "Dýrið sem er líklegast til að flétta á sér hárið",
    "Dýrið sem er líklegast til að fara í klifurhúsið",
    "Dýrið sem er líklegast til að eiga ættingja í stjórnsýslunni",
    "Dýrið sem er líklegast til að fara á ólympíuleikana",
    "Dýrið sem best í að ganga með skartgripi",
    "Dýrið sem er best að nota skæri",
    "Dýrið sem er best að dansa",
    "Dýrið sem er best í að baka brauð",
    "Dýrið sem er best í að láta þig halda að það sé mánudagur",
    "Dýrið sem er best í að taka ljósmyndir þannig að það sést ekki í allt ennið á fólki",
    "Dýrið sem er best í að koma sér í sambönd til að fá netflix aðgang",
    "Dýrið sem er best í að fussa yfir einhverju sem því finnst ekki vera fréttir",
    "Dýrið sem er best í að hvetja aðra áfram",
    "Dýrið sem getur borðað mest á einum degi",
    "Dýrið sem gæti ekki lifað af án þess að skoða instagram á 5 mínútna fresti",
    "Dýrið sem gæti verið tölvunarfræðingur",
    "Dýrið sem kann flesta tóna",
    "Dýrið sem kann flesta brandarana",
    "Dýrið sem hefur farið oftast í ísbúð",
    "Dýrið sem best kann að meta jazz tónlist",
    "Dýrið sem kann símanúmer allra vina sinna utanað",
    "Dýrið sem getur talið upp í hæsta töluna",
    "Dýrið sem kann flest þjóðlög",
    "Dýrið sem er best í að fljúga flugdreka",
    "Dýrið sem er mest fyrir poppkorn",
    "Dýrið sem er mest fyrir að lita með vaxlitum",
    "Dýrið sem stóð sig best í íþróttum í skóla",
    "Dýrið sem stóð sig best í hlíðniskóla",
    "Dýrið sem fékk að fara einum bekk á undan í skóla",
    "Dýrið sem fór óhefðbunda leið í gegnum skólakerfið",
    "Dýrið sem flest eru hrædd við",
    "Dýrið sem yrði sett á gríðarstórt veggteppi á barnaspítala",
    "Dýrið sem var valið vinsælasti nemandinn",
    "Dýrið sem var forseti nemendafélagsins",
    "Dýrið sem var kosið líklegast til að ná árangri",
    "Dýrið sem flest fólk vill ekki sjá í strætó",
    "Dýrið sem fólk myndi furða sig mest á ef það myndi banka upp á",
    "Dýrið sem fólk hringir í þegar eitthvað er að rafmagninu",
    "Dýrið sem fólk hringir í þegar það þarf skattaráðgjöf",
    "Dýrið sem fólk hringir í þegar það missir af flugi",
    "Dýrið sem fólki kaus sem næsta atriði í Eurovision",
    "Dýrið sem fólk vill að hætti að skrifa bókagagnrýni",
    "Dýrið sem fólk reynir að forðast í fermingum",
    "Dýrið sem fólk kann að meta að mætti í ferminguna",
    "Dýrið sem fólk öfundar af hæfileikum í körfubolta",
    "Dýrið sem var kostið ólíklegast til að ná árangri í fornleifafræði",
    "Dýrið sem var valið þriðji besti keppandinn í fegurðarsamkeppni",
    "Dýrið sem notar minnstu skóna",
    "Dýrið sem ferðast um heiminn til að taka þátt í fegurðarsamkeppnum",
    "Líklegast til að byrja samsæriskenningar um fuglaflutninga",
    "Myndi örugglega verða útilokað af samfélagsmiðlum fyrir að deila of miklu",
    "Líklegast til að safna gamaldags flöskatöppum",
    "Myndi líklega finna upp nýjan dans",
    "Líklegast til að verða áhugasöm um duldarrænar staðreyndir",
    "Myndi örugglega nefna börnin sín eftir himintunglum",
    "Líklegast til að geyma salernispappír í neyðartilvikum",
    "Myndi líklega tala við húsplöntur eins og þær væru bestu vinir",
    "Líklegast til að hafa sterkar skoðanir um áferð mismunandi efna",
    "Myndi örugglega raða kryddunum í stafrófsröð",
    "Líklegast til að falla í Wikipedia-kanínuholu um miðalda stjórnarfar",
    "Líklegast til að klæðast mistlitum sokkum",
    "Líklegast til að safna gúmmíöndum frá mismunandi löndum",
    "Myndi örugglega starfa sem látbragðsleikari úti á götu fyrir smáaura",
    "Líklegast til að trúa því að dúfur séu ríkisnjósnarar",
    "Kann að tala fllest tungumál",
    "Líklegast til að ljúga",
    "Myndi líklega syngja í sturtu",
    "Líklegast til að dansa í rigningunni",
    "Myndi örugglega hlæja af eigin brandara",
    "Líklegast til að tala við sjálfan sig",
    "Myndi líklegast gleyma afmælisdegi vina sinna",
    "Líklegast til að missa af strætó",
    "Myndi örugglega tala hátt í bíó",
    "Líklegast til að gleyma hvar það lagði bílinn",
    "Líklegast til að prófa nýjan mat sem lítur undarlega út",
    "Líklegast til að villast",
    "Myndi örugglega hlæja í óviðeigandi aðstæðum",
    "Myndi líklegast gleyma nafni þeirra sem það hefur hitt oft áður",
];
