// English weird conditions for the Adult Mode Generator
export const weirdConditions = [
    "Most likely to start a conspiracy theory about bird migration",
    "Would definitely get banned from social media for oversharing",
    "Most likely to collect vintage bottle caps as a hobby",
    "Would probably invent a new dance move",
    "Most likely to become obsessed with obscure trivia",
    "Would definitely name their children after celestial objects",
    "Most likely to hoard napkins from fast food restaurants",
    "Would probably talk to houseplants like they're best friends",
    "Most likely to have strong opinions about the texture of different fabrics",
    "Would definitely organize their spice rack alphabetically",
    "Most likely to fall down a Wikipedia rabbit hole about medieval farming",
    "Would probably wear mismatched socks on purpose",
    "Most likely to collect rubber ducks from different countries",
    "Would definitely have a secret identity as a street mime",
    "Most likely to believe that pigeons are government spies",
    // Translated from Icelandic
    "Most likely to be in a circus",
    "Most likely to be a pet",
    "Most likely to be in a swimming pool",
    "Most likely to be president",
    "Most likely to eat a mouse",
    "Most likely to live in Iceland",
    "Most likely mascot for a swimming pool",
    "Most likely mascot for a clock company",
    "Most likely to talk a lot on the phone",
    "Most likely to walk with a backpack",
    "Most likely to be the pet of the President of Iceland",
    "Most likely to write a book about their life",
    "Most likely to visit a library",
    "Most likely to cook",
    "Most likely to sleep in the attic",
    "Most likely to play a musical instrument",
    "Most likely to be in the news",
    "Most likely to learn to read",
    "Most likely to be found in a hot tub",
    "Most likely to get cozy on the couch",
    "Most likely to go horseback riding",
    "Most likely to wear glasses",
    "Most likely to get their ears pierced",
    "Most likely to order sourdough pizza",
    "Most likely to go into cheese making",
    "Most likely to be in a good mood",
    "Most likely to be in a bad mood",
    "Most likely to want to be your friend",
    "Most likely to introduce a new pudding at the grocery store",
    "Most likely to compete in badminton",
    "Most likely to become a Danish furniture designer",
    "Most likely to design video games",
    "Most likely to design new types of pasta",
    "Most likely to massage another animal",
    "Most likely to knit a sweater",
    "Most likely to braid their hair",
    "Most likely to go to the climbing gym",
    "Most likely to have relatives in government",
    "Most likely to go to the Olympics",
    "Best at wearing jewelry",
    "Best at using scissors",
    "Best at dancing",
    "Best at baking bread",
    "Best at making you think it's Monday",
    "Best at taking photos where you can't see the whole forehead",
    "Best at getting into relationships to get Netflix access",
    "Best at complaining about something they don't think is news",
    "Best at encouraging others",
    "Can eat the most in one day",
    "Couldn't survive without checking Instagram every 5 minutes",
    "Could be a computer scientist",
    "Knows the most songs",
    "Knows the most jokes",
    "Has been to an ice cream shop the most times",
    "Best at appreciating jazz music",
    "Knows all their friends' phone numbers by heart",
    "Can count to the highest number",
    "Knows the most folk songs",
    "Best at flying kites",
    "Most into popcorn",
    "Most into coloring with crayons",
    "Performed best in sports at school",
    "Performed best in obedience school",
    "Got to skip ahead a grade in school",
    "Took an unconventional path through the school system",
    "Most animals are afraid of",
    "Would be put on a giant wall tapestry in a children's hospital",
    "Was voted most popular student",
    "Was student council president",
    "Was voted most likely to succeed",
    "Most people don't want to see on the bus",
    "People would be most surprised to see knocking at their door",
    "People call when something's wrong with the electricity",
    "People call when they need tax advice",
    "People call when they miss their flight",
    "People voted for as the next Eurovision act",
    "People want to stop writing book reviews",
    "People try to avoid at confirmations",
    "People appreciate showing up to the confirmation",
    "People envy for their basketball skills",
    "Was voted least likely to succeed in archaeology",
    "Was voted third best contestant in a beauty pageant",
    "Wears the smallest shoes",
    "Travels the world to compete in beauty pageants",
    "Most likely to start conspiracy theories about bird migration",
    "Would definitely share too much and get banned from social media",
    "Most likely to collect old bottle caps",
    "Would probably invent a new dance",
    "Most likely to become interested in mysterious facts",
    "Would definitely name their children after celestial objects",
    "Most likely to hoard toilet paper for emergencies",
    "Would probably talk to houseplants like they're best friends",
    "Most likely to have strong opinions about fabric textures",
    "Would definitely arrange spices alphabetically",
    "Most likely to fall into a Wikipedia rabbit hole about medieval government",
    "Most likely to wear mismatched socks",
    "Most likely to collect rubber ducks from different countries",
    "Would definitely work as a street mime for spare change",
    "Most likely to believe pigeons are government spies",
    "Knows the most languages",
    "Most likely to lie",
    "Would probably sing in the shower",
    "Most likely to dance in the rain",
    "Would definitely laugh at their own jokes",
    "Most likely to talk to themselves",
    "Would probably forget friends' birthdays",
    "Most likely to miss the bus",
    "Would definitely talk loudly in the movies",
    "Most likely to forget where they parked the car",
    "Most likely to try strange-looking food",
    "Most likely to get lost",
    "Would definitely laugh at inappropriate times",
    "Would probably forget the name of people they've met many times before"
];
